sudo: require

addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - cmake-data
      - cmake
      - lcov

language: cpp

compiler: gcc-7

before_install:
 - CXX=g++-7
 # Install GoogleTest/Mock
 - sudo apt-get install -y libgtest-dev valgrind
 - sudo wget https://github.com/google/googletest/archive/release-1.8.0.tar.gz
 - sudo tar xf release-1.8.0.tar.gz
 - cd googletest-release-1.8.0
 - sudo cmake -DBUILD_SHARED_LIBS=ON .
 - sudo make
 - sudo cp -a googletest/include/gtest /usr/include
 - sudo cp -a googlemock/include/gmock /usr/include
 - sudo cp -a googlemock/gtest/libgtest_main.so googlemock/gtest/libgtest.so /usr/lib/
 - sudo cp -a googlemock/libgmock_main.so googlemock/libgmock.so /usr/lib/
 - cd "${TRAVIS_BUILD_DIR}"
install:
 - mkdir build
 - cd build
 - cmake ..
 - make
script:
 - ./geometry_test

env:
  - CODECOV_TOKEN="0606decb-cc12-4416-b7f2-ee578bb99605"
after_success:
  # Create lcov report
  # capture coverage info
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory . --capture --output-file coverage.info
  # filter out system and extra files.
  # To also not include test code in coverage add them with full path to the patterns: '*/tests/*'
  - lcov --remove coverage.info '/usr/*' "${HOME}"'/.cache/*' --output-file coverage.info
  # output coverage data for debugging (optional)
  - lcov --list coverage.info
  # Uploading to CodeCov
  # '-f' specifies file(s) to use and disables manual coverage gathering and file search which has already been done above
  - bash <(curl -s https://codecov.io/bash) -t uuid-repo-token
  - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"
